version: '3.9'
services:
  ceph:
    image: ubuntu
    environment:
      http_proxy:
      https_proxy:
      no_proxy:
    volumes:
      - ceph-data:/data
    working_dir: /data
volumes:
  ceph-data:
    driver_opts:
      type: ceph
      device: mon1.example.com,mon2.example.com,mon3.example.com:/
      o: name=${CEPH_NAME},mds_namespace=${CEPH_NAMESPACE},secret=${CEPH_SECRET}